version: 0.2

env:
  variables:
    SOLUTION: .\AWSCODE-CLI.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.8

phases:
  build:
    commands:
     
artifacts:
  files:
    - .\AWSCODE-CLI\bin\Debug\*